### PR TITLE
Downgrade rust_2018_idioms from forbid to warn

### LINKED ISSUE #5: Crate fails to build with pin-project-lite v0.1.9
The crate fails to build with `pin-project-lite` at `v0.1.9` printing the following

```plain
error[E0453]: allow(explicit_outlives_requirements) overruled by outer forbid(rust_2018_idioms)
  --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/duplexify-1.2.1/src/lib.rs:42:1
   |
34 |   #![forbid(unsafe_code, rust_2018_idioms)]
   |                          ---------------- `forbid` level set here
...
42 | / pin_project_lite::pin_project! {
43 | |     /// Combine a reader + writer into a duplex of `Read` + `Write`.
44 | |     #[derive(Debug)]
45 | |     pub struct Duplex<R, W> {
...  |
50 | |     }
51 | | }
   | |_^ overruled by previous forbid
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0453`.
error: could not compile `duplexify`.
```

See https://github.com/taiki-e/pin-project-lite/issues/34

### PR DESCRIPTION
**Pull request by taiki-e**
Fixes #5

See also https://github.com/taiki-e/pin-project-lite/issues/33#issuecomment-700494455

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -47,7 +47,7 @@ $ cargo add duplexify
 ```
 
 ## Safety
-This crate uses ``#![deny(unsafe_code)]`` to ensure everything is implemented in
```
Comment (jbr) [inline README.md:50]: Is this particular change needed? Rustc docs and the nomicon both refer specifically to this `#![forbid(unsafe_code)]` invocation

**Review by jbr — APPROVED** [review]
